SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS VEHICLE_CROSSING;
DROP TABLE IF EXISTS SIGNAL_LANE;
DROP TABLE IF EXISTS LANE;
DROP TABLE IF EXISTS SIGNAL;
DROP TABLE IF EXISTS VEHICLE;




/* Create Tables */

CREATE TABLE LANE
(
	ID bigint unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(30),
	PRIMARY KEY (ID)
);


CREATE TABLE SIGNAL
(
	ID bigint unsigned NOT NULL AUTO_INCREMENT,
	NAME varchar(20) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE SIGNAL_LANE
(
	ID bigint unsigned NOT NULL AUTO_INCREMENT,
	SIGNAL_ID bigint unsigned NOT NULL,
	FROM_LANE_ID bigint unsigned NOT NULL,
	TO_LANE_ID bigint unsigned NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FROM_TO UNIQUE (SIGNAL_ID, FROM_LANE_ID, TO_LANE_ID)
);


CREATE TABLE VEHICLE
(
	REG_NO varchar(10) NOT NULL,
	TYPE varchar(10) NOT NULL,
	MODEL varchar(10),
	PRIMARY KEY (REG_NO),
	UNIQUE (REG_NO)
);


CREATE TABLE VEHICLE_CROSSING
(
	REG_NO varchar(10) NOT NULL,
	SIGNAL_LANE_ID bigint unsigned NOT NULL,
	DATE datetime NOT NULL,
	SPEED float unsigned NOT NULL,
	UNIQUE (REG_NO)
);



/* Create Foreign Keys */

ALTER TABLE SIGNAL_LANE
	ADD FOREIGN KEY (TO_LANE_ID)
	REFERENCES LANE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIGNAL_LANE
	ADD FOREIGN KEY (FROM_LANE_ID)
	REFERENCES LANE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIGNAL_LANE
	ADD FOREIGN KEY (SIGNAL_ID)
	REFERENCES SIGNAL (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VEHICLE_CROSSING
	ADD FOREIGN KEY (SIGNAL_LANE_ID)
	REFERENCES SIGNAL_LANE (ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE VEHICLE_CROSSING
	ADD FOREIGN KEY (REG_NO)
	REFERENCES VEHICLE (REG_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



